Repository nyttikord/nerdkord, pull requests merged in 2025-06, with the labels that each got.

#12 [Feat] Add margins to latex output
  commands/latex.go
  libs/img/pad.go
  libs/latex2png/compile.go
Labels: enhancement

#15 [Bug] delete temporary files
  commands/latex.go
  libs/latex2png/compile.go
Labels: bug

#18 [Feat] latex preprocessing
  commands/latex.go
  libs/latex2png/compile.go
  libs/latex2png/options.go
  libs/latex2png/preprocessor.go
  libs/latex2png/preprocessor_test.go
Labels: bug, enhancement

#25 [Feat] Get source
  commands/latex.go
  commands/profile.go
  main.go
Labels: enhancement

#29 [Feat] .env support
  go.mod
  go.sum
  main.go
Labels: enhancement
